### ISSUE TITLE
make a scripts to grep/detect errors in the result of `make again`

### ISSUE THREAD

**Issue by HAOYUatHZ** [scroll-tech/scroll-prover#23]

**Comment by richardgreg** [comment]
This was closed and reopened. @HAOYUatHZ is this issue still open?

**Comment by silathdiir** [comment]
Hi @richardgreg , I am sorry that seems this issue is expired. Will close it if no update and new comments in some days.

**Comment by HAOYUatHZ** [comment]
yes I can confirm that it's expired

**Comment by richardgreg** [comment]
Thanks for the clarification fellas. Are there open issues - in here or in other repos - that can be labelled as "good first issues?" I'm looking to start small and work my way up to more complex issues.
