### ISSUE TITLE
feat: add API to check circuit capacity

### ISSUE THREAD

**Issue by lispc** [scroll-tech/scroll-prover#94]
Problem:
currently we use some heuristic mechansim in l2geth to prevent big batch overflowing circuit, like block_num_limit, total_gas_limit, etc.  But it is not the final/correct solution. Circuit have much more limitation factors than these relatively simpler metrics, for example, sum(calldata), sum(keccak_len), sum(code_copy_len), etc all have some limitations. It is not wise to **reimplement these fast changing rules again in golang**, instead circuits should provide a simple stable  capacity check interface to be used by sequencer(rust->CGO->golang).

p-code in infra side:

Solution1(stateless):
```
let mut blocks = Vec::new();
while true {
  let mut cur_blocks = blocks.clone();
  cur_blocks.push(fetch_new_block());
  if CapacityChecker::check(cur_blocks) {
    // circuit can process this batch, continue try
    blocks = cur_blocks;
    continue;
  } else {
    //  circuit cannot process the batch with last block, need to exclude the last block
    break;
  }
}
prover.prove_batch(blocks)
```

Solution2(stateful):
More efficient, need some extra work in circuit side, i prefer this way.

```
let mut checker = CapacityChecker::new();
while true {
   if checker.try_add_block(fetch_new_block()) {
     continue;
   } else {
     // checker cannot process the last block, and **will not add it to its internal queue**.
      break;
   }
}
prover.prove_batch(checker.get_batch());
```

Problems:

what if circuit cannot even process one block / one tx?

tx level: must implement some limitation(max tx len, max keccak len etc..) in l2geth to prevent these txs..so even worse case single evil attack tx cannot overflow circuit.

block level: (A) always make one l2block == one tx to simplify these checks..  or (B) allow l2block containing multi txs, but add a "fallback" mechanism in l2geth, reorg blocks and split big block into smaller blocks..

**Comment by Thegaram** [comment]
> what if circuit cannot even process one block / one tx?

Seems like we cannot keep Ethereum's block gas limit logic, we need to add additional limitation based on this `CapacityChecker`.

What do you think will be the runtime cost of CapacityChecker? Will it have to traverse through all opcodes executed in the tx?

**Comment by lispc** [comment]
It need to traverse through all opcodes. We have no implementation, by from theoretical guess, i think it will be of 0.1s/0.2s.  No heavy.
